services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    command: bun dev --host 0.0.0.0

  lint:
    build:
      context: .
      dockerfile: docker/lint/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    command: bun lint

  lint-fix:
    build:
      context: .
      dockerfile: docker/lint/Dockerfile
    volumes:
      - .:/app
    command: bun lint:fix

  serve:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - .:/app
    command: bun serve --host 0.0.0.0

  coverage:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - .:/app
    command: bun coverage

  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - .:/app
    command: bun test

  build:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    volumes:
      - ./dist:/export/dist
    command: |
      sh -c "
        bun vite build &&
        mkdir -p /export &&
        cp -R dist/* /export/dist/ &&
        echo 'Build artifacts copied to host volume'
      "
