services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: bun run dev --host 0.0.0.0

  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - .:/app
    command: bun test

  build:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    # No volume mapping here during the build
    command: |
      sh -c "
        bun vite build &&
        mkdir -p /export &&
        cp -R dist /export &&
        chmod -R 777 /export/dist
      "
    volumes:
      # Only mount the host's dist directory after the build
      - ./dist:/export/dist
