name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/bun-install@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun run biome check ./lib ./tests

      - name: Run tests
        run: bun test

      - name: Build
        run: bun build
  
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@V3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: hellajs/core:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max