name: Docker CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start dev server in Docker
        run: |
          docker compose up -d --build dev
          sleep 10        
      - name: Check if dev server is running
        run: |
          curl --retry 3 --retry-delay 5 -f http://localhost:5173/ || (docker compose logs dev && exit 1)       
      - name: Shutdown dev server
        run: docker compose down
        if: always()

  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests in Docker
        run: docker compose up --exit-code-from test test

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build library with Docker
        run: |
          mkdir -p dist
          docker compose up --build build
